stages:
  get_data:
    cmd: python sentiment_model_training/modeling/get_data.py
    outs:
    - data/raw.tsv
  preprocess:
    cmd: python sentiment_model_training/modeling/preprocess.py
    deps:
    - data/raw.tsv
    - sentiment_model_training/modeling/preprocess.py
    outs:
    - data/labels.pkl
    - data/processed.npy
    - model/bag_of_words.pkl
  train:
    cmd: python sentiment_model_training/modeling/train.py
    deps:
    - data/labels.pkl
    - data/processed.npy
    - model/bag_of_words.pkl
    - sentiment_model_training/modeling/train.py
    outs:
    - data/X_test.pkl
    - data/y_test.pkl
    - model/model.pkl
  evaluate:
    cmd: python sentiment_model_training/modeling/evaluate.py
    deps:
    - data/X_test.pkl
    - data/y_test.pkl
    - model/model.pkl
    - sentiment_model_training/modeling/evaluate.py
    metrics:
    - metrics.json:
        cache: false
