name: Release
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      run: python run.py

    - name: Upload model
    - uses: softprops/action-gh-release@v1
      with:
        files: model.pkl

    - name: Upload bag of words
    - uses: softprops/action-gh-release@v1
      with:
        files: bag_of_words.pkl

      
      
